# Project-wide Gradle settings.
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.code.style=official

# Gradle
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
org.gradle.daemon=false
org.gradle.configureondemand=false

# React Native
reactNativeArchitectures=arm64-v8a
newArchEnabled=false
hermesEnabled=true
org.gradle.java.home=/opt/homebrew/Cellar/openjdk@17/17.0.20.1/libexec/openjdk.jdk/Contents/Home
android.suppressUnsupportedCompileSdk=35
