import { Permission, RoleConfig, UserRole } from '../types';

export const ALL_PERMISSIONS: Permission[] = [
  'users.view',
  'users.edit',
  'users.suspend',
  'users.search',
  'students.view',
  'students.edit',
  'clients.view',
  'clients.approve',
  'clients.reject',
  'clients.suspend',
  'jobs.view',
  'jobs.create',
  'jobs.edit',
  'jobs.approve',
  'jobs.reject',
  'jobs.delete',
  'applications.view',
  'applications.manage',
  'notifications.view',
  'notifications.send',
  'reports.view',
  'reports.manage',
  'app_versions.view',
  'app_versions.create',
  'app_versions.update',
  'staff.view',
  'staff.create',
  'staff.edit',
  'staff.delete',
  'roles.view',
  'roles.create',
  'roles.edit',
  'roles.delete',
  'settings.view',
  'settings.update',
  'audit_logs.view',
  'maintenance.manage',
  'feature_flags.manage',
  'categories.manage',
];

export const DEFAULT_ROLE_CONFIGS: Record<UserRole, RoleConfig> = {
  superuser: {
    id: 'superuser',
    role: 'superuser',
    name: 'Superuser',
    description: 'Complete unrestricted control over entire platform',
    permissions: [...ALL_PERMISSIONS],
    isSystem: true,
  },
  admin: {
    id: 'admin',
    role: 'admin',
    name: 'Administrator',
    description: 'Full management of users, jobs, approvals, versions, and logs',
    permissions: [
      'users.view',
      'users.edit',
      'users.suspend',
      'users.search',
      'students.view',
      'students.edit',
      'clients.view',
      'clients.approve',
      'clients.reject',
      'clients.suspend',
      'jobs.view',
      'jobs.create',
      'jobs.edit',
      'jobs.approve',
      'jobs.reject',
      'jobs.delete',
      'applications.view',
      'applications.manage',
      'notifications.view',
      'notifications.send',
      'reports.view',
      'reports.manage',
      'app_versions.view',
      'app_versions.create',
      'app_versions.update',
      'staff.view',
      'roles.view',
      'settings.view',
      'settings.update',
      'audit_logs.view',
      'maintenance.manage',
      'feature_flags.manage',
      'categories.manage',
    ],
    isSystem: true,
  },
  staff: {
    id: 'staff',
    role: 'staff',
    name: 'Staff Member',
    description: 'Configurable operational staff with assigned permissions',
    permissions: [
      'jobs.view',
      'jobs.approve',
      'jobs.reject',
      'reports.view',
      'users.view',
    ],
    isSystem: true,
  },
  moderator: {
    id: 'moderator',
    role: 'moderator',
    name: 'Content Moderator',
    description: 'Reviews jobs, contents, and handles abuse reports',
    permissions: [
      'jobs.view',
      'jobs.approve',
      'jobs.reject',
      'jobs.delete',
      'reports.view',
      'reports.manage',
    ],
    isSystem: true,
  },
  support: {
    id: 'support',
    role: 'support',
    name: 'Customer Support',
    description: 'Investigates user accounts, searches users, and views profiles',
    permissions: [
      'users.view',
      'users.search',
      'reports.view',
      'notifications.view',
    ],
    isSystem: true,
  },
  student: {
    id: 'student',
    role: 'student',
    name: 'Student',
    description: 'Platform student user',
    permissions: [],
    isSystem: true,
  },
  client: {
    id: 'client',
    role: 'client',
    name: 'Client Employer',
    description: 'Platform client / project poster',
    permissions: [],
    isSystem: true,
  },
};
